INSERT INTO SEXO (SEXO) VALUES ('MASC');
INSERT INTO SEXO (SEXO) VALUES ('FEM');

-- Os inserts devem ser ordenados alfabeticamente
INSERT INTO REGIAO (REGIAO) VALUES ('AGUAS CLARAS');
INSERT INTO REGIAO (REGIAO) VALUES ('ARNIQUEIRA');
INSERT INTO REGIAO (REGIAO) VALUES ('BRAZLANDIA');
INSERT INTO REGIAO (REGIAO) VALUES ('BRASILIA');
INSERT INTO REGIAO (REGIAO) VALUES ('CANDANGOLANDIA');
INSERT INTO REGIAO (REGIAO) VALUES ('CEILANDIA');
INSERT INTO REGIAO (REGIAO) VALUES ('CRUZEIRO');
INSERT INTO REGIAO (REGIAO) VALUES ('ESTRUTURAL');
INSERT INTO REGIAO (REGIAO) VALUES ('FERCAL');
INSERT INTO REGIAO (REGIAO) VALUES ('GAMA');
INSERT INTO REGIAO (REGIAO) VALUES ('GUARA');
INSERT INTO REGIAO (REGIAO) VALUES ('ITAPOA');
INSERT INTO REGIAO (REGIAO) VALUES ('JARDIM BOTANICO');
INSERT INTO REGIAO (REGIAO) VALUES ('LAGO NORTE');
INSERT INTO REGIAO (REGIAO) VALUES ('LAGO SUL');
INSERT INTO REGIAO (REGIAO) VALUES ('NUCLEO BANDEIRANTE');
INSERT INTO REGIAO (REGIAO) VALUES ('PARANOA');
INSERT INTO REGIAO (REGIAO) VALUES ('PARK WAY');
INSERT INTO REGIAO (REGIAO) VALUES ('PLANALTINA');
INSERT INTO REGIAO (REGIAO) VALUES ('RECANTO DAS EMAS');
INSERT INTO REGIAO (REGIAO) VALUES ('RIACHO FUNDO');
INSERT INTO REGIAO (REGIAO) VALUES ('RIACHO FUNDO 2');
INSERT INTO REGIAO (REGIAO) VALUES ('SAMAMBAIA');
INSERT INTO REGIAO (REGIAO) VALUES ('SANTA MARIA');
INSERT INTO REGIAO (REGIAO) VALUES ('SAO SEBASTIAO');
INSERT INTO REGIAO (REGIAO) VALUES ('SIA');
INSERT INTO REGIAO (REGIAO) VALUES ('SOL NASCENTE/POR DO SOL');
INSERT INTO REGIAO (REGIAO) VALUES ('SOBRADINHO');
INSERT INTO REGIAO (REGIAO) VALUES ('SOBRADINHO 2');
INSERT INTO REGIAO (REGIAO) VALUES ('SUDOESTE');
INSERT INTO REGIAO (REGIAO) VALUES ('TAGUATINGA');
INSERT INTO REGIAO (REGIAO) VALUES ('VARJAO DO TORTO');
INSERT INTO REGIAO (REGIAO) VALUES ('VICENTE PIRES');


INSERT INTO ANO (ANO) VALUES (2016);
INSERT INTO ANO (ANO) VALUES (2017);
INSERT INTO ANO (ANO) VALUES (2018);
INSERT INTO ANO (ANO) VALUES (2019);
INSERT INTO ANO (ANO) VALUES (2020);
INSERT INTO ANO (ANO) VALUES (2021);
INSERT INTO ANO (ANO) VALUES (2022);
INSERT INTO ANO (ANO) VALUES (2023);

INSERT INTO FAIXA_ETARIA (FAIXA_ETARIA) VALUES ('ATÉ 11 ANOS');
INSERT INTO FAIXA_ETARIA (FAIXA_ETARIA) VALUES ('DE 12 A 17 ANOS');
INSERT INTO FAIXA_ETARIA (FAIXA_ETARIA) VALUES ('DE 18 A 30 ANOS');
INSERT INTO FAIXA_ETARIA (FAIXA_ETARIA) VALUES ('DE 31 A 50 ANOS');
INSERT INTO FAIXA_ETARIA (FAIXA_ETARIA) VALUES ('MAIS DE 50 ANOS');
INSERT INTO FAIXA_ETARIA (FAIXA_ETARIA) VALUES ('NÃO INFORMADO');
